-- MySQL Script generated by MySQL Workbench
-- 02/24/17 21:08:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestion_stage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_stage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_stage` DEFAULT CHARACTER SET utf8 ;
USE `gestion_stage` ;

-- -----------------------------------------------------
-- Table `gestion_stage`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`fonction` (
  `fonctionId` INT NOT NULL AUTO_INCREMENT,
  `fonctionNom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`fonctionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`utilisateur` (
  `utilisateurId` INT NOT NULL AUTO_INCREMENT,
  `utilisateurUserName` VARCHAR(25) NOT NULL,
  `utilisateurMdp` VARCHAR(50) NOT NULL,
  `fonction_fonctionId` INT NOT NULL,
  PRIMARY KEY (`utilisateurId`, `fonction_fonctionId`),
  INDEX `fk_utilisateur_fonction_idx` (`fonction_fonctionId` ASC),
  CONSTRAINT `fk_utilisateur_fonction`
    FOREIGN KEY (`fonction_fonctionId`)
    REFERENCES `gestion_stage`.`fonction` (`fonctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`entreprise` (
  `entrepriseId` INT NOT NULL AUTO_INCREMENT,
  `entrepriseRaisonSociale` VARCHAR(45) NOT NULL,
  `adresseNoRue` INT NOT NULL,
  `adresseRue` VARCHAR(45) NOT NULL,
  `adresseComplement` VARCHAR(45) NULL,
  `adresseCdePostal` INT NOT NULL,
  `adresseVille` VARCHAR(45) NOT NULL,
  `adressePays` VARCHAR(45) NOT NULL,
  `entrepriseMail` VARCHAR(45) NOT NULL,
  `entrepriseTel` INT NOT NULL,
  `entrepriseSecteurAc` VARCHAR(45) NOT NULL,
  `utilisateur_utilisateurId` INT NOT NULL,
  PRIMARY KEY (`entrepriseId`, `utilisateur_utilisateurId`),
  INDEX `fk_entreprise_utilisateur1_idx` (`utilisateur_utilisateurId` ASC),
  CONSTRAINT `fk_entreprise_utilisateur1`
    FOREIGN KEY (`utilisateur_utilisateurId`)
    REFERENCES `gestion_stage`.`utilisateur` (`utilisateurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`etudiant` (
  `etudiantId` INT NOT NULL AUTO_INCREMENT,
  `etudiantNom` VARCHAR(20) NOT NULL,
  `etudiantPrenom` VARCHAR(20) NOT NULL,
  `adresseNoRue` INT NOT NULL,
  `adresseRue` VARCHAR(45) NOT NULL,
  `adresseComplement` VARCHAR(45) NULL,
  `adresseCdePostal` INT NOT NULL,
  `adresseVille` VARCHAR(45) NOT NULL,
  `adressePays` VARCHAR(45) NOT NULL,
  `etudiantNomFormation` VARCHAR(45) NOT NULL,
  `etudiantUniversite` VARCHAR(45) NOT NULL,
  `etudiantMail` VARCHAR(45) NOT NULL,
  `etudiantTel` INT NOT NULL,
  `utilisateur_utilisateurId` INT NOT NULL,
  PRIMARY KEY (`etudiantId`, `utilisateur_utilisateurId`),
  UNIQUE INDEX `etudiantNomFormation_UNIQUE` (`etudiantNomFormation` ASC),
  INDEX `fk_etudiant_utilisateur1_idx` (`utilisateur_utilisateurId` ASC),
  CONSTRAINT `fk_etudiant_utilisateur1`
    FOREIGN KEY (`utilisateur_utilisateurId`)
    REFERENCES `gestion_stage`.`utilisateur` (`utilisateurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`administrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`administrateur` (
  `administrateurId` INT NOT NULL AUTO_INCREMENT,
  `administrateurNom` VARCHAR(45) NOT NULL,
  `administrateurPrenom` VARCHAR(45) NOT NULL,
  `adresseNoRue` INT NOT NULL,
  `adresseRue` VARCHAR(45) NOT NULL,
  `adresseComplement` VARCHAR(45) NULL,
  `adresseCdePostal` INT NOT NULL,
  `adresseVille` VARCHAR(45) NOT NULL,
  `adressePays` VARCHAR(45) NOT NULL,
  `administrateurMail` VARCHAR(45) NOT NULL,
  `administrateurTel` INT NOT NULL,
  `utilisateur_utilisateurId` INT NOT NULL,
  PRIMARY KEY (`administrateurId`, `utilisateur_utilisateurId`),
  INDEX `fk_administrateur_utilisateur1_idx` (`utilisateur_utilisateurId` ASC),
  CONSTRAINT `fk_administrateur_utilisateur1`
    FOREIGN KEY (`utilisateur_utilisateurId`)
    REFERENCES `gestion_stage`.`utilisateur` (`utilisateurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`domaine_offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`domaine_offre` (
  `domaineId` INT NOT NULL AUTO_INCREMENT,
  `domaineIntitule` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`domaineId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`offre_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`offre_stage` (
  `offreId` INT NOT NULL AUTO_INCREMENT,
  `domaine_domaineId` INT NOT NULL,
  `offreLibelle` VARCHAR(45) NOT NULL,
  `offreDescrption` VARCHAR(200) NOT NULL,
  `offreDateDebut` DATE NOT NULL,
  `offreDuree` VARCHAR(45) NOT NULL,
  `offreCheminStockage` VARCHAR(150) NOT NULL,
  `offreValide` CHAR NOT NULL,
  PRIMARY KEY (`offreId`, `domaine_domaineId`),
  INDEX `fk_offre_stage_domaine_offre1_idx` (`domaine_domaineId` ASC),
  CONSTRAINT `fk_offre_stage_domaine_offre1`
    FOREIGN KEY (`domaine_domaineId`)
    REFERENCES `gestion_stage`.`domaine_offre` (`domaineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_stage`.`candidature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_stage`.`candidature` (
  `offre_offreId` INT NOT NULL,
  `etudiant_etudiantId` INT NOT NULL,
  `candidatureDate` DATE NOT NULL,
  PRIMARY KEY (`offre_offreId`, `etudiant_etudiantId`),
  INDEX `fk_offre_stage_has_etudiant_etudiant1_idx` (`etudiant_etudiantId` ASC),
  INDEX `fk_offre_stage_has_etudiant_offre_stage1_idx` (`offre_offreId` ASC),
  CONSTRAINT `fk_offre_stage_has_etudiant_offre_stage1`
    FOREIGN KEY (`offre_offreId`)
    REFERENCES `gestion_stage`.`offre_stage` (`offreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offre_stage_has_etudiant_etudiant1`
    FOREIGN KEY (`etudiant_etudiantId`)
    REFERENCES `gestion_stage`.`etudiant` (`etudiantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
