package Views.Profil;

import Controllers.AdministrateurController;
import Models.Administrateur;
import Models.DAO.AdministrateurDAO;
import Models.DAO.DAO;
import Models.DAO.UtilisateurDAO;
import Models.Utilisateur;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Allam on 31/03/2017.
 */
public class ProfilAdministrateurView extends JPanel {
    private JPanel pProfilAdministrateur;
    private JLabel lAnnonce;
    private JPanel pContenu;
    private JLabel lNom;
    private JTextField tfNom;
    private JLabel lPrenom;
    private JTextField tfPrenom;
    private JLabel lAdresse;
    private JPanel pAdresse1;
    private JTextField tfNoRue;
    private JTextField tfRue;
    private JTextField tfComplement;
    private JPanel pAdresse2;
    private JTextField tfCdePostal;
    private JTextField tfVille;
    private JTextField tfPays;
    private JLabel lMail;
    private JTextField tfMail;
    private JLabel lTel;
    private JTextField tfTel;
    private JPanel pBouttons;
    private JButton bCreationAdmin;
    private JButton bModifier;
    private JButton bModifierPseudoMdp;
    private JPanel pBouttonsValidation;
    private JButton bValider;
    private JButton bAnnuler;

    public ProfilAdministrateurView(Administrateur admin) {
        tfNom.setText(admin.getAdministrateurNom());
        tfPrenom.setText(admin.getAdministrateurPrenom());
        tfNoRue.setText(String.valueOf(admin.getAdresseNoRue()));
        tfRue.setText(admin.getAdresseRue());
        tfComplement.setText(admin.getAdresseComplement());
        tfCdePostal.setText(String.valueOf(admin.getAdresseCdePostal()));
        tfVille.setText(admin.getAdresseVille());
        tfPays.setText(admin.getAdressePays());
        tfMail.setText(admin.getAdministrateurMail());
        tfTel.setText(String.valueOf(admin.getAdministrateurTel()));

        bCreationAdmin.addActionListener(new BCreationAdminListener());
        bModifier.addActionListener(new BModifierListener());
        bModifierPseudoMdp.addActionListener(new BModifierPseudoMdpListener());
        bValider.addActionListener(new BValiderListener());
        bAnnuler.addActionListener(new BAnnulerListener());
    }

    public JPanel getpProfilAdministrateur() {
        return pProfilAdministrateur;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pProfilAdministrateur = new JPanel();
        pProfilAdministrateur.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        pProfilAdministrateur.setPreferredSize(new Dimension(1090, 595));
        lAnnonce = new JLabel();
        lAnnonce.setText("Mon profil");
        pProfilAdministrateur.add(lAnnonce, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pContenu = new JPanel();
        pContenu.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        pProfilAdministrateur.add(pContenu, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lNom = new JLabel();
        lNom.setText("Nom");
        pContenu.add(lNom, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNom = new JTextField();
        tfNom.setEnabled(false);
        pContenu.add(tfNom, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lPrenom = new JLabel();
        lPrenom.setText("Prenom");
        pContenu.add(lPrenom, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfPrenom = new JTextField();
        tfPrenom.setEnabled(false);
        pContenu.add(tfPrenom, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lAdresse = new JLabel();
        lAdresse.setText("Adresse");
        pContenu.add(lAdresse, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pAdresse1 = new JPanel();
        pAdresse1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        pContenu.add(pAdresse1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tfNoRue = new JTextField();
        tfNoRue.setEnabled(false);
        tfNoRue.setText("");
        pAdresse1.add(tfNoRue, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfRue = new JTextField();
        tfRue.setEnabled(false);
        pAdresse1.add(tfRue, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfComplement = new JTextField();
        tfComplement.setEnabled(false);
        pContenu.add(tfComplement, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pAdresse2 = new JPanel();
        pAdresse2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        pContenu.add(pAdresse2, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tfCdePostal = new JTextField();
        tfCdePostal.setEnabled(false);
        pAdresse2.add(tfCdePostal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfVille = new JTextField();
        tfVille.setEnabled(false);
        pAdresse2.add(tfVille, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfPays = new JTextField();
        tfPays.setEnabled(false);
        pAdresse2.add(tfPays, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lMail = new JLabel();
        lMail.setText("Mail");
        pContenu.add(lMail, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfMail = new JTextField();
        tfMail.setEnabled(false);
        pContenu.add(tfMail, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lTel = new JLabel();
        lTel.setText("Téléphone");
        pContenu.add(lTel, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfTel = new JTextField();
        tfTel.setEnabled(false);
        pContenu.add(tfTel, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        pContenu.add(spacer1, new GridConstraints(0, 3, 7, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pContenu.add(spacer2, new GridConstraints(0, 1, 7, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        pBouttons = new JPanel();
        pBouttons.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        pProfilAdministrateur.add(pBouttons, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bCreationAdmin = new JButton();
        bCreationAdmin.setText("Créer un nouvel administrateur");
        pBouttons.add(bCreationAdmin, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bModifier = new JButton();
        bModifier.setText("Modifier mes informations");
        pBouttons.add(bModifier, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bModifierPseudoMdp = new JButton();
        bModifierPseudoMdp.setText("Modifier mon login et mon mot de passe");
        pBouttons.add(bModifierPseudoMdp, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        pProfilAdministrateur.add(spacer3, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        pProfilAdministrateur.add(spacer4, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        pProfilAdministrateur.add(spacer5, new GridConstraints(1, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        pProfilAdministrateur.add(spacer6, new GridConstraints(1, 3, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        pBouttonsValidation = new JPanel();
        pBouttonsValidation.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        pBouttonsValidation.setEnabled(true);
        pProfilAdministrateur.add(pBouttonsValidation, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bValider = new JButton();
        bValider.setEnabled(false);
        bValider.setText("Valider");
        pBouttonsValidation.add(bValider, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bAnnuler = new JButton();
        bAnnuler.setEnabled(false);
        bAnnuler.setText("Annuler");
        pBouttonsValidation.add(bAnnuler, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer7 = new Spacer();
        pBouttonsValidation.add(spacer7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer8 = new Spacer();
        pBouttonsValidation.add(spacer8, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer9 = new Spacer();
        pProfilAdministrateur.add(spacer9, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer10 = new Spacer();
        pProfilAdministrateur.add(spacer10, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pProfilAdministrateur;
    }

    class BCreationAdminListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            AdministrateurDAO aDAO = new AdministrateurDAO();
            AdministrateurController administrateurController = new AdministrateurController(aDAO);
            InscriptionAdminView inscriptionAdminView = new InscriptionAdminView(administrateurController);
        }
    }

    class BModifierListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            tfNom.setEnabled(true);
            tfPrenom.setEnabled(true);
            tfNoRue.setEnabled(true);
            tfRue.setEnabled(true);
            tfComplement.setEnabled(true);
            tfCdePostal.setEnabled(true);
            tfVille.setEnabled(true);
            tfPays.setEnabled(true);
            tfMail.setEnabled(true);
            tfTel.setEnabled(true);
            bValider.setEnabled(true);
            bAnnuler.setEnabled(true);
        }
    }

    class BModifierPseudoMdpListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            UtilisateurDAO uDAO = new UtilisateurDAO();
            Utilisateur utilisateur = uDAO.find(new Utilisateur().getId());
            ChangementMdpView changementMdpView = new ChangementMdpView(utilisateur);
        }
    }

    class BValiderListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Utilisateur u = new Utilisateur();
            DAO<Administrateur> aDAO = new AdministrateurDAO();
            Administrateur admin = aDAO.find(u.getIdU());

            admin.setAdministrateurNom(tfNom.getText());
            admin.setAdministrateurPrenom(tfPrenom.getText());
            admin.setAdresseNoRue(Integer.valueOf(tfNoRue.getText()));
            admin.setAdresseRue(tfRue.getText());
            admin.setAdresseComplement(tfComplement.getText());
            admin.setAdresseCdePostal(Integer.valueOf(tfCdePostal.getText()));
            admin.setAdresseVille(tfVille.getText());
            admin.setAdressePays(tfPays.getText());
            admin.setAdministrateurMail(tfMail.getText());
            admin.setAdministrateurTel(Integer.valueOf(tfTel.getText()));

            aDAO.update(admin);

            tfNom.setEnabled(false);
            tfPrenom.setEnabled(false);
            tfNoRue.setEnabled(false);
            tfRue.setEnabled(false);
            tfComplement.setEnabled(false);
            tfCdePostal.setEnabled(false);
            tfVille.setEnabled(false);
            tfPays.setEnabled(false);
            tfMail.setEnabled(false);
            tfTel.setEnabled(false);
            bValider.setEnabled(false);
            bAnnuler.setEnabled(false);
        }
    }

    class BAnnulerListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            tfNom.setEnabled(false);
            tfPrenom.setEnabled(false);
            tfNoRue.setEnabled(false);
            tfRue.setEnabled(false);
            tfComplement.setEnabled(false);
            tfCdePostal.setEnabled(false);
            tfVille.setEnabled(false);
            tfPays.setEnabled(false);
            tfMail.setEnabled(false);
            tfTel.setEnabled(false);
            bValider.setEnabled(false);
            bAnnuler.setEnabled(false);
        }
    }
}